package database

import (
	"time"

	"github.com/biodoia/goleapifree/pkg/models"
	"github.com/google/uuid"
)

// getFreeAPIProviders restituisce la lista pre-popolata di provider gratuiti
func getFreeAPIProviders() []models.Provider {
	now := time.Now()

	return []models.Provider{
		// Tier 1 - Premium Free Providers
		{
			ID:          uuid.New(),
			Name:        "OpenRouter Free",
			Type:        models.ProviderTypeFree,
			Status:      models.ProviderStatusActive,
			BaseURL:     "https://openrouter.ai/api/v1",
			AuthType:    models.AuthTypeAPIKey,
			Tier:        1,
			DiscoveredAt: now,
			Source:      "manual",
			SupportsStreaming: true,
			SupportsTools:     true,
			SupportsJSON:      true,
		},
		{
			ID:          uuid.New(),
			Name:        "Google AI Studio",
			Type:        models.ProviderTypeFree,
			Status:      models.ProviderStatusActive,
			BaseURL:     "https://generativelanguage.googleapis.com/v1beta",
			AuthType:    models.AuthTypeAPIKey,
			Tier:        1,
			DiscoveredAt: now,
			Source:      "manual",
			SupportsStreaming: true,
			SupportsTools:     false,
			SupportsJSON:      true,
		},
		{
			ID:          uuid.New(),
			Name:        "Groq",
			Type:        models.ProviderTypeFreemium,
			Status:      models.ProviderStatusActive,
			BaseURL:     "https://api.groq.com/openai/v1",
			AuthType:    models.AuthTypeAPIKey,
			Tier:        1,
			DiscoveredAt: now,
			Source:      "manual",
			SupportsStreaming: true,
			SupportsTools:     true,
			SupportsJSON:      true,
		},
		{
			ID:          uuid.New(),
			Name:        "Cerebras",
			Type:        models.ProviderTypeFreemium,
			Status:      models.ProviderStatusActive,
			BaseURL:     "https://api.cerebras.ai/v1",
			AuthType:    models.AuthTypeAPIKey,
			Tier:        1,
			DiscoveredAt: now,
			Source:      "manual",
			SupportsStreaming: true,
			SupportsTools:     false,
			SupportsJSON:      true,
		},
		{
			ID:          uuid.New(),
			Name:        "Mistral La Plateforme",
			Type:        models.ProviderTypeFreemium,
			Status:      models.ProviderStatusActive,
			BaseURL:     "https://api.mistral.ai/v1",
			AuthType:    models.AuthTypeAPIKey,
			Tier:        1,
			DiscoveredAt: now,
			Source:      "manual",
			SupportsStreaming: true,
			SupportsTools:     true,
			SupportsJSON:      true,
		},
		{
			ID:          uuid.New(),
			Name:        "Cohere Free Tier",
			Type:        models.ProviderTypeFreemium,
			Status:      models.ProviderStatusActive,
			BaseURL:     "https://api.cohere.ai/v1",
			AuthType:    models.AuthTypeBearer,
			Tier:        1,
			DiscoveredAt: now,
			Source:      "manual",
			SupportsStreaming: true,
			SupportsTools:     false,
			SupportsJSON:      true,
		},
		{
			ID:          uuid.New(),
			Name:        "GitHub Models",
			Type:        models.ProviderTypeFree,
			Status:      models.ProviderStatusActive,
			BaseURL:     "https://models.inference.ai.azure.com",
			AuthType:    models.AuthTypeAPIKey,
			Tier:        1,
			DiscoveredAt: now,
			Source:      "manual",
			SupportsStreaming: true,
			SupportsTools:     false,
			SupportsJSON:      true,
		},
		{
			ID:          uuid.New(),
			Name:        "Cloudflare Workers AI",
			Type:        models.ProviderTypeFree,
			Status:      models.ProviderStatusActive,
			BaseURL:     "https://api.cloudflare.com/client/v4/accounts",
			AuthType:    models.AuthTypeBearer,
			Tier:        1,
			DiscoveredAt: now,
			Source:      "manual",
			SupportsStreaming: false,
			SupportsTools:     false,
			SupportsJSON:      true,
		},

		// Tier 2 - Community/Proxy Providers
		{
			ID:          uuid.New(),
			Name:        "zukijourney",
			Type:        models.ProviderTypeFree,
			Status:      models.ProviderStatusActive,
			BaseURL:     "https://zukijourney.xyzbot.net/v1",
			AuthType:    models.AuthTypeNone,
			Tier:        2,
			DiscoveredAt: now,
			Source:      "github",
			SupportsStreaming: true,
			SupportsTools:     false,
			SupportsJSON:      true,
		},
		{
			ID:          uuid.New(),
			Name:        "ElectronHub",
			Type:        models.ProviderTypeFree,
			Status:      models.ProviderStatusActive,
			BaseURL:     "https://api.electronhub.top/v1",
			AuthType:    models.AuthTypeNone,
			Tier:        2,
			DiscoveredAt: now,
			Source:      "github",
			SupportsStreaming: true,
			SupportsTools:     false,
			SupportsJSON:      true,
		},
		{
			ID:          uuid.New(),
			Name:        "NagaAI",
			Type:        models.ProviderTypeFree,
			Status:      models.ProviderStatusActive,
			BaseURL:     "https://api.naga.ac/v1",
			AuthType:    models.AuthTypeNone,
			Tier:        2,
			DiscoveredAt: now,
			Source:      "github",
			SupportsStreaming: true,
			SupportsTools:     false,
			SupportsJSON:      true,
		},

		// Local providers
		{
			ID:          uuid.New(),
			Name:        "Ollama Local",
			Type:        models.ProviderTypeLocal,
			Status:      models.ProviderStatusActive,
			BaseURL:     "http://localhost:11434/v1",
			AuthType:    models.AuthTypeNone,
			Tier:        1,
			DiscoveredAt: now,
			Source:      "manual",
			SupportsStreaming: true,
			SupportsTools:     false,
			SupportsJSON:      true,
		},
	}
}
