// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/biodoia/goleapifree/pkg/models"
)

func StatsPanel(stats []models.ProviderStats) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"stats-grid\"><div class=\"stat-box\"><div class=\"stat-label\">TOTAL REQUESTS</div><div class=\"stat-value\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(formatTotalRequests(stats))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/stats.templ`, Line: 12, Col: 55}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div class=\"stat-graph\">████████████████░░░░</div></div><div class=\"stat-box\"><div class=\"stat-label\">SUCCESS RATE</div><div class=\"stat-value\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(formatSuccessRate(stats))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/stats.templ`, Line: 19, Col: 53}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"stat-graph\">█████████████████░░░</div></div><div class=\"stat-box\"><div class=\"stat-label\">AVG LATENCY</div><div class=\"stat-value\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(formatAvgLatency(stats))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/stats.templ`, Line: 26, Col: 52}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><div class=\"stat-graph\">██████████░░░░░░░░░░</div></div><div class=\"stat-box\"><div class=\"stat-label\">COST SAVED</div><div class=\"stat-value\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(formatCostSaved(stats))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/stats.templ`, Line: 33, Col: 51}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div class=\"stat-graph\">███████████████████░</div></div><div class=\"stat-box stat-box-wide\"><div class=\"stat-label\">PROVIDERS STATUS</div><div class=\"providers-status-grid\"><div class=\"status-item\"><span class=\"status-dot status-active\">█</span> Active: <span class=\"status-count\">12</span></div><div class=\"status-item\"><span class=\"status-dot status-down\">█</span> Down: <span class=\"status-count\">2</span></div><div class=\"status-item\"><span class=\"status-dot status-warn\">█</span> Warning: <span class=\"status-count\">1</span></div></div></div><div class=\"stat-box stat-box-wide\"><div class=\"stat-label\">REQUEST TIMELINE (LAST HOUR)</div><div class=\"timeline\"><pre class=\"timeline-graph\">20 │                                    █ 15 │                      █             █ 10 │          █     █     █       █     █ 5 │    █     █     █     █  █    █  █  █ 0 │────┴─────┴─────┴─────┴──┴────┴──┴──┴───── 00   10    20    30    40   50   60  min</pre></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func formatTotalRequests(stats []models.ProviderStats) string {
	var total int64
	for _, s := range stats {
		total += s.TotalRequests
	}
	if total > 1000000 {
		return fmt.Sprintf("%.1fM", float64(total)/1000000)
	}
	if total > 1000 {
		return fmt.Sprintf("%.1fK", float64(total)/1000)
	}
	return fmt.Sprintf("%d", total)
}

func formatSuccessRate(stats []models.ProviderStats) string {
	if len(stats) == 0 {
		return "0.0%"
	}
	var totalRate float64
	for _, s := range stats {
		totalRate += s.SuccessRate
	}
	avgRate := totalRate / float64(len(stats))
	return fmt.Sprintf("%.1f%%", avgRate*100)
}

func formatAvgLatency(stats []models.ProviderStats) string {
	if len(stats) == 0 {
		return "0ms"
	}
	var totalLatency int64
	for _, s := range stats {
		totalLatency += int64(s.AvgLatencyMs)
	}
	avgLatency := totalLatency / int64(len(stats))
	return fmt.Sprintf("%dms", avgLatency)
}

func formatCostSaved(stats []models.ProviderStats) string {
	var total float64
	for _, s := range stats {
		total += s.CostSaved
	}
	return fmt.Sprintf("$%.2f", total)
}

var _ = templruntime.GeneratedTemplate
